# Generated by Django 5.2.9 on 2026-06-25 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='soil_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
