# Generated by Django 5.2.9 on 2026-06-28 17:56

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation_api', '0002_field_soil_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('zone_id', models.AutoField(primary_key=True, serialize=False)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('cluster', models.PositiveSmallIntegerField()),
                ('area_m2', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='irrigation_api.field')),
            ],
            options={
                'db_table': 'zone',
            },
        ),
        migrations.CreateModel(
            name='SatelliteData',
            fields=[
                ('sat_id', models.AutoField(primary_key=True, serialize=False)),
                ('acquisition_date', models.DateTimeField()),
                ('ndvi', models.FloatField()),
                ('rvi', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satellite_data', to='irrigation_api.zone')),
            ],
            options={
                'db_table': 'satellite_data',
                'ordering': ['-acquisition_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='zone',
            constraint=models.UniqueConstraint(fields=('field', 'cluster'), name='unique_field_cluster'),
        ),
        migrations.AddIndex(
            model_name='satellitedata',
            index=models.Index(fields=['zone', 'acquisition_date'], name='satellite_d_zone_id_ea1236_idx'),
        ),
        migrations.AddConstraint(
            model_name='satellitedata',
            constraint=models.UniqueConstraint(fields=('zone', 'acquisition_date'), name='unique_zone_date'),
        ),
    ]
