# Generated by Django 5.2.9 on 2026-06-28 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation_api', '0003_zone_satellitedata_zone_unique_field_cluster_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('weather_id', models.AutoField(primary_key=True, serialize=False)),
                ('observation_time', models.DateTimeField()),
                ('temperature_2m', models.FloatField()),
                ('relative_humidity_2m', models.FloatField()),
                ('rain', models.FloatField()),
                ('surface_pressure', models.FloatField()),
                ('et0_fao_evapotranspiration', models.FloatField()),
                ('vapour_pressure_deficit', models.FloatField()),
                ('wind_speed_10m', models.FloatField()),
                ('temperature_80m', models.FloatField()),
                ('soil_moisture_1_to_3cm', models.FloatField()),
                ('soil_temperature_6cm', models.FloatField()),
                ('direct_radiation', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_data', to='irrigation_api.zone')),
            ],
            options={
                'db_table': 'weather',
                'ordering': ['-observation_time'],
                'indexes': [models.Index(fields=['zone', 'observation_time'], name='weather_zone_id_8ebe5f_idx')],
                'constraints': [models.UniqueConstraint(fields=('zone', 'observation_time'), name='unique_zone_weather_datetime')],
            },
        ),
    ]
