# Generated by Django 5.2.9 on 2026-06-28 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation_api', '0004_weather'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropType',
            fields=[
                ('crop_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('scientific_name', models.CharField(blank=True, max_length=150)),
                ('kc_initial', models.FloatField()),
                ('kc_mid', models.FloatField()),
                ('kc_end', models.FloatField()),
                ('initial_stage_days', models.PositiveSmallIntegerField()),
                ('development_stage_days', models.PositiveSmallIntegerField()),
                ('mid_stage_days', models.PositiveSmallIntegerField()),
                ('late_stage_days', models.PositiveSmallIntegerField()),
                ('max_root_depth_m', models.FloatField()),
                ('max_crop_height_m', models.FloatField()),
                ('depletion_fraction', models.FloatField(help_text='Fraction of Total Available Water (p)')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'crop_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SoilType',
            fields=[
                ('soil_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('texture', models.CharField(max_length=50)),
                ('field_capacity', models.FloatField(help_text='Volumetric water content at field capacity (m³/m³)')),
                ('permanent_wilting_point', models.FloatField(help_text='Volumetric water content at permanent wilting point (m³/m³)')),
                ('saturation', models.FloatField(help_text='Volumetric water content at saturation (m³/m³)')),
                ('available_water_mm_per_m', models.FloatField(help_text='Available water capacity (mm/m)')),
                ('infiltration_rate_mm_hr', models.FloatField()),
                ('hydraulic_conductivity_mm_day', models.FloatField()),
                ('bulk_density', models.FloatField(help_text='g/cm³')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'soil_type',
                'ordering': ['name'],
            },
        ),
    ]
