# Generated by Django 5.2.9 on 2026-06-28 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation_api', '0005_croptype_soiltype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='crop_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fields', to='irrigation_api.croptype'),
        ),
        migrations.AlterField(
            model_name='field',
            name='soil_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fields', to='irrigation_api.soiltype'),
        ),
    ]
