# Generated by Django 5.2.9 on 2026-06-28 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation_api', '0006_alter_field_crop_type_alter_field_soil_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evapotranspiration',
            fields=[
                ('et_id', models.AutoField(primary_key=True, serialize=False)),
                ('calculation_time', models.DateTimeField()),
                ('eto', models.FloatField(help_text='Reference evapotranspiration (mm)')),
                ('kc', models.FloatField(help_text='Crop coefficient')),
                ('etc', models.FloatField(help_text='Crop evapotranspiration (mm)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('satellite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evapotranspiration', to='irrigation_api.satellitedata')),
                ('weather', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evapotranspiration', to='irrigation_api.weather')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evapotranspiration', to='irrigation_api.zone')),
            ],
            options={
                'db_table': 'evapotranspiration',
                'ordering': ['-calculation_time'],
                'constraints': [models.UniqueConstraint(fields=('zone', 'calculation_time'), name='unique_zone_et')],
            },
        ),
    ]
