# Generated by Django 5.2.9 on 2026-06-29 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation_api', '0007_evapotranspiration'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilWaterBalance',
            fields=[
                ('swb_id', models.AutoField(primary_key=True, serialize=False)),
                ('calculation_time', models.DateTimeField()),
                ('taw', models.FloatField(help_text='Total Available Water (mm)')),
                ('depletion', models.FloatField(help_text='Root zone depletion (mm)')),
                ('soil_water_balance', models.FloatField(help_text='Available soil water after the balance update (mm)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evapotranspiration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_water_balance', to='irrigation_api.evapotranspiration')),
                ('weather', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_water_balance', to='irrigation_api.weather')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_water_balance', to='irrigation_api.zone')),
            ],
            options={
                'db_table': 'soil_water_balance',
                'ordering': ['-calculation_time'],
                'constraints': [models.UniqueConstraint(fields=('zone', 'calculation_time'), name='unique_zone_soil_water_balance')],
            },
        ),
    ]
