# Generated by Django 5.2.9 on 2026-06-29 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation_api', '0008_soilwaterbalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrrigationRecommendation',
            fields=[
                ('recommendation_id', models.AutoField(primary_key=True, serialize=False)),
                ('recommendation_time', models.DateTimeField()),
                ('mad', models.FloatField()),
                ('corrected_water_balance', models.FloatField()),
                ('irrigation_required', models.BooleanField()),
                ('recommended_amount', models.FloatField()),
                ('actual_amount', models.FloatField(blank=True, help_text='Actual irrigation applied (training label)', null=True)),
                ('zone_color', models.CharField(blank=True, max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('soil_water_balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='irrigation_api.soilwaterbalance')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='irrigation_api.zone')),
            ],
        ),
    ]
